[versions]
agp = "8.10.1"
kotlin = "1.9.25"
android-compileSdk = "36"
android-targetSdk = "35"
android-minSdk = "24"
coroutines = "1.8.1"
lifecycle = "2.7.0"
lifecycleTesting = "2.2.0"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.12.0"
browser = "1.8.0"
recyclerview = "1.3.2"
legacy = "1.0.0"
swipeRefresh = "1.1.0"
transition = "1.4.1"
annotation = "1.7.1"
fragment = "1.7.1"
viewPager = "1.0.0"
viewPager2 = "1.0.0"
preferences = "1.2.1"
collection = "1.4.0"
activity = "1.9.0"
constraintLayout = "2.1.4"
androidxTest = "1.5.0"
androidxJunit = "1.1.5"
espresso = "3.5.1"
mockk = "1.13.10"
koin = "3.5.6"
junit4 = "4.13.2"
firebaseCore = "21.1.1"
firebaseBom = "32.8.1"
timber = "4.7.1"
flipper = "0.154.0"
soloader = "0.10.1"
hilt = "2.51.1"
hiltCompiler = "1.1.0"
hiltNavCompose = "1.2.0"
compose = "1.10.0"
composeMaterialIcons = "1.7.8"
composeCompiler = "1.5.15"
composeActivity = "1.9.0"
composeLifecycle = "2.7.0"
navigation = "2.7.7"
desugar = "2.0.4"
googleServices = "4.4.2"
crashlyticsGradle = "2.9.9"
ktlintGradle = "12.1.0"
[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-legacy = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy" }
androidx-swipe-refresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefresh" }
androidx-transition = { module = "androidx.transition:transition", version.ref = "transition" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preferences" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewPager" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewPager2" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
androidx-lifecycle-test = { module = "androidx.arch.core:core-testing", version.ref = "lifecycleTesting" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

junit4 = { module = "junit:junit", version.ref = "junit4" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTest" }

firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }

desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterialIcons" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "composeLifecycle" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
androidx-compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "composeLifecycle" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavCompose" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
hilt-lifecycle-viewmodel = { module = "androidx.hilt:hilt-lifecycle-viewmodel", version.ref = "hiltCompiler" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsGradle" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
